packageExtensions:
  '@fastify/aws-lambda@*':
    dependencies:
      fastify: 4.14.1
      aws-lambda: '^1.0.7'
      '@types/aws-lambda': '^8.10.114'
  '@fastify/cookie@*':
    dependencies:
      fastify: 4.14.1
  '@anatine/esbuild-decorators@*':
    dependencies:
      tslib: '*'
  '@nestjs-modules/ioredis@*':
    dependencies:
      tslib: '*'
  '@golevelup/nestjs-discovery@*':
    dependencies:
      '@nestjs/common': '*'
      '@nestjs/core': '*'
  '@nestjs/common@*':
    dependencies:
      reflect-metadata: '*'
      rxjs: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

supportedArchitectures:
  cpu:
    - x86
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.5.0.cjs
