compressionLevel: mixed

enableGlobalCache: true

packageExtensions:
  "@anatine/esbuild-decorators@*":
    dependencies:
      tslib: "*"
  "@fastify/aws-lambda@*":
    dependencies:
      "@types/aws-lambda": ^8.10.114
      aws-lambda: ^1.0.7
      fastify: 4.14.1
  "@fastify/cookie@*":
    dependencies:
      fastify: 4.14.1
  "@golevelup/nestjs-discovery@*":
    peerDependencies:
      "@nestjs/common": 9.3.10
      "@nestjs/core": 9.3.10
  "@nestjs-modules/ioredis@*":
    dependencies:
      tslib: "*"
  "@nestjs/common@*":
    dependencies:
      cache-manager: "*"
      class-transformer: "*"
      class-validator: "*"
      reflect-metadata: "*"
      rxjs: "*"

supportedArchitectures:
  cpu:
    - x86
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.5.3.cjs
