version: '3.7'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  md-dev1:
    image: registry.gitlab.com/md-dev1/mini-dice-docker-images:latest.dev
    environment:
      - VIRTUAL_HOST=localhost
