import { getScenarioRoute, SkillRouteType } from '@packages/scenario-routing';
import { IndexSkill } from '../../skill-group-lib/constants';
import { SCENARIO_NAMES } from '../scenarios.constants';

export const D1ScenarioRoutes = getScenarioRoute(SCENARIO_NAMES.D1, {
  landEventRealEstate: ['earned', 'takenOver'],
  landEventMapCycle: ['earnedCash'],
  landEventMoneyCollection: ['otherUserReceivedCash'],
  landEventMinigame: ['newRecords'],

  defaultStart: [IndexSkill],
  mapStarter: [IndexSkill],
  carAccident: [IndexSkill],
  rps: [IndexSkill, 'submit'],
  nightFood: [IndexSkill],
  land1: [IndexSkill, 'submit'],
  gameDev: [IndexSkill],
  noBus: [IndexSkill],
  moneyCollection1: [IndexSkill],
  pickedItem: [IndexSkill],
  fire: [IndexSkill],
  stock: [IndexSkill, 'buy', 'sell', 'buyMore'],
  minigameEasy: [IndexSkill, 'submit'],
  lottery: [IndexSkill],
  land2: [IndexSkill, 'submit'],
  hacked: [IndexSkill],
  land3: [IndexSkill, 'submit'],
  horseGameble: [IndexSkill],
  earfquake: [IndexSkill],
  partTimeWork: [IndexSkill],
  land4: [IndexSkill, 'submit'],
  zeroWait: [IndexSkill],
  pickedWallet: [IndexSkill],
  moneyCollection2: [IndexSkill],
  book: [IndexSkill],
  land5: [IndexSkill, 'submit'],
  moneyCollection3: [IndexSkill],
  dragonMoney: [IndexSkill],
  fastCar: [IndexSkill],
  stockDown: [IndexSkill],
  stockUp: [IndexSkill],
  minigameHard: [IndexSkill, 'submit'],
  land6: [IndexSkill, 'submit'],
  travel: [IndexSkill],
  witch: [IndexSkill],
  minigameInfinity: [IndexSkill, 'submit'],
  moneyCollection4: [IndexSkill],
} as const);

export const OrderedD1ScenarioRoutes: SkillRouteType[] = [
  D1ScenarioRoutes.skillGroups.mapStarter,
  D1ScenarioRoutes.skillGroups.carAccident,
  D1ScenarioRoutes.skillGroups.rps,
  D1ScenarioRoutes.skillGroups.land1,
  D1ScenarioRoutes.skillGroups.nightFood,
  D1ScenarioRoutes.skillGroups.moneyCollection1,
  D1ScenarioRoutes.skillGroups.gameDev,
  D1ScenarioRoutes.skillGroups.pickedItem,
  D1ScenarioRoutes.skillGroups.fire,
  D1ScenarioRoutes.skillGroups.stock,
  D1ScenarioRoutes.skillGroups.land2,
  D1ScenarioRoutes.skillGroups.minigameEasy,
  D1ScenarioRoutes.skillGroups.lottery,
  D1ScenarioRoutes.skillGroups.land3,
  D1ScenarioRoutes.skillGroups.partTimeWork,
  D1ScenarioRoutes.skillGroups.land4,
  D1ScenarioRoutes.skillGroups.pickedWallet,
  D1ScenarioRoutes.skillGroups.moneyCollection2,
  D1ScenarioRoutes.skillGroups.book,
  D1ScenarioRoutes.skillGroups.land5,
  D1ScenarioRoutes.skillGroups.moneyCollection3,
  D1ScenarioRoutes.skillGroups.dragonMoney,
  D1ScenarioRoutes.skillGroups.fastCar,
  D1ScenarioRoutes.skillGroups.stockUp,
  D1ScenarioRoutes.skillGroups.stockDown,
  D1ScenarioRoutes.skillGroups.minigameHard,
  D1ScenarioRoutes.skillGroups.land6,
  D1ScenarioRoutes.skillGroups.minigameInfinity,
].map((skillGroup) => skillGroup.skills[IndexSkill]);
