name: '@apps/server - Update Version'

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  apps-server-update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git 유저 설정 | Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run npm-ci
        run: yarn

      - name: 버전 높이기 | Bump Version
        run: |
          yarn lerna:bootstrap
          yarn lerna:version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
